module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
  darkMode: ['class', 'class'],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        'primary-light': '#FFE8E8',
        'primary-dark': '#E85555',
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        'secondary-light': '#E8F8F7',
        'secondary-dark': '#45B7AF',
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        'accent-light': '#FFF3E0',
        'accent-dark': '#F57C00',
        selection: '#FFE0B2',
        highlight: '#FFF9C4',
        border: 'hsl(var(--border))',
        'gray-warm': '#F8F9FA',
        'gray-light': '#F5F5F5',
        white: '#FFFFFF',
        'text-primary': '#2C3E50',
        'text-secondary': '#5A6C7D',
        'text-muted': '#95A5A6',
        'dark-bg': '#1A1A1A',
        'dark-bg-secondary': '#2D2D2D',
        'dark-bg-tertiary': '#404040',
        'dark-border': '#404040',
        'dark-text-primary': '#E5E5E5',
        'dark-text-secondary': '#B0B0B0',
        'dark-text-muted': '#808080',
        'gradient-sunset': 'linear-gradient(135deg, #FF6B6B 0%, #FFA726 100%)',
        'gradient-ocean': 'linear-gradient(135deg, #4ECDC4 0%, #45B7AF 100%)',
        'gradient-warm': 'linear-gradient(135deg, #FFA726 0%, #FF6B6B 100%)',
        overlay: 'rgba(0,0,0,0.6)',
        'overlay-light': 'rgba(255,255,255,0.5)',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          1: 'hsl(var(--chart-1))',
          2: 'hsl(var(--chart-2))',
          3: 'hsl(var(--chart-3))',
          4: 'hsl(var(--chart-4))',
          5: 'hsl(var(--chart-5))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
